BEGIN TRANSACTION;

DROP TABLE IF EXISTS PESSOAS;

CREATE TABLE PESSOAS(
    ID INT PRIMARY KEY AUTOINCREMENT
    NOME TEXT NOT NULL
    CPF TEXT NOT NULL
    IDADE TEXT NOT NULL
    CIDADE INT NOT NULL
);


INSERT INTO CIDADES(NOME,ESTADO,POPULAÇÃO)
    VALUES